export const CREATE_PRODUCT_IMAGE_QUERY_KEY = 'CREATE_PRODUCT_IMAGE_QUERY_KEY';
export const UPDATE_PRODUCT_IMAGE_QUERY_KEY = 'UPDATE_PRODUCT_IMAGE_QUERY_KEY';
export const DELETE_PRODUCT_IMAGE_QUERY_KEY = 'DELETE_PRODUCT_IMAGE_QUERY_KEY';
