export const CREATE_EXTERNAL_ID_QUERY_KEY = 'CREATE_EXTERNAL_ID_QUERY_KEY';
export const UPDATE_EXTERNAL_ID_QUERY_KEY = 'UPDATE_EXTERNAL_ID_QUERY_KEY';
export const DELETE_EXTERNAL_ID_QUERY_KEY = 'DELETE_EXTERNAL_ID_QUERY_KEY';
