export const UPDATE_PRODUCT_QUERY_QEY = 'UPDATE_PRODUCT_QUERY_QEY';
export const CREATE_PRODUCT_QUERY_QEY = 'CREATE_PRODUCT_QUERY_QEY';
export const DELETE_PRODUCT_QUERY_QEY = 'DELETE_PRODUCT_QUERY_QEY';
