import '../styles/globals.css';
import 'react-loading-skeleton/dist/skeleton.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/free-mode';
import 'swiper/css/thumbs';

import type { AppProps } from 'next/app';
import DataComponent from '../components/DataComponent/DataComponent';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { ThemeProvider } from 'styled-components';
import { theme } from '../contsants/theme';
import { wrapper } from '../store';
import { useEffect, useState } from 'react';

function MyApp({ Component, ...rest }: AppProps) {
    const { store, props } = wrapper.useWrappedStore(rest);

    const [isHydrated, setIsHydrated] = useState(false);

    useEffect(() => {
        setIsHydrated(true);
    }, []);

    return (
        <Provider store={store}>
            <Head>
                <title>У Михалыча</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DataComponent />
            {isHydrated && (
                <ThemeProvider theme={theme}>
                    <Component {...props.pageProps} />
                </ThemeProvider>
            )}
        </Provider>
    );
}

export default MyApp;
